project:
  type: book
  output-dir: docs

book:
  title: "R resource collection"
  author: "Konstantin Engelmayer & Emilio Sánchez"
  date: "19.7.2025"
  chapters:
    - index.qmd
    - intro.qmd
    - raster.qmd
    - vector.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



